"use strict";
const displayer = (dado) => console.log(dado);
let nomeCompleto = 'Arthur Correia da Silva';
displayer(nomeCompleto);
let funcao = "Desenvolvedor Front-End";
displayer(funcao);
let empresa = `Amazon`;
displayer(empresa);
let informacoes = `Nome   : ${nomeCompleto} \nEmpresa: ${empresa} \nFunção : ${funcao}`;
displayer(informacoes);
